language: rust
rust: nightly

jobs:
  include:
    - os: linux
      dist: bionic

    - os: osx

before_script:
  - rustup component add rustfmt

script:
  - cargo build
  - cargo fmt --all -- --check
