[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["cdylib"]

[dependencies]
url = "2.1.1"
tokio = { version = "0.2.21", features = [ "rt-threaded", "sync" ] }
tracing = "0.1.15"
tracing-subscriber = "0.2.6"
async-std = { version = "1.6.2", features = [ "unstable" ] }
clap = "2.33.1"
async-trait = "0.1.36"
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.weechat]
git = "https://github.com/poljar/rust-weechat"
features = ["async", "config_macro"]

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
default-features = false
features = ["encryption", "sqlite-cryptostore", "messages"]
