[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.65"
futures = "0.3.1"
url = "2.1.0"
tokio = "0.2.0-alpha.6"
async-std = { version = "1.1.0", features = [ "unstable" ] }
pipe-channel = "1.2.2"
clap = "2.33.0"

matrix-nio = { git = "https://github.com/poljar/nio-rust" }

weechat = { git = "https://github.com/poljar/rust-weechat" }
weechat-sys = { git = "https://github.com/poljar/rust-weechat" }
async-task = { git = "https://github.com/poljar/async-task" }
