[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.66"
url = "2.1.1"
tokio = { version = "0.2.9", features = [ "rt-threaded" ] }
async-std = { version = "1.4.0", features = [ "unstable" ] }
clap = "2.33.0"

matrix-nio = { git = "https://github.com/poljar/nio-rust" }

weechat = { path = "/home/poljar/werk/weechat/rust-weechat/weechat-rs/", features = ["async-executor"] }
weechat-sys = { path = "/home/poljar/werk/weechat/rust-weechat/weechat-sys" }
