[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.65"
futures = "0.3.1"
url = "2.1.0"
tokio = "0.2.0-alpha.6"
async-std = { version = "1.0.1", features = [ "unstable" ] }
pipe-channel = "1.2.2"

matrix-nio = { path = "/home/poljar/werk/priv/nio-rust/" }

weechat = { path = "/home/poljar/werk/misc/rust-weechat/weechat-rs" }
weechat-sys = { path = "/home/poljar/werk/misc/rust-weechat/weechat-sys" }
async-task = { path = "/home/poljar/werk/misc/async-task" }
