[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.66"
futures = "0.3.1"
url = "2.1.1"
tokio = { version = "0.2.9", features = [ "rt-threaded" ] }
async-std = { version = "1.4.0", features = [ "unstable" ] }
async-task = "1.2.1"
pipe-channel = "1.2.2"
clap = "2.33.0"

matrix-nio = { path = "/home/poljar/werk/priv/nio-rust/" }

weechat = { path = "/home/poljar/werk/misc/rust-weechat/weechat-rs/" }
weechat-sys = { path = "/home/poljar/werk/misc/rust-weechat/weechat-sys" }
