[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["cdylib"]

[dependencies]
url = "2.2.0"
futures = "0.3.8"
tokio = { version = "0.2.22", features = [ "rt-threaded", "sync" ] }
dashmap = "3.11.10"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
async-std = { version = "1.8.0", features = [ "unstable" ] }
clap = "2.33.3"
async-trait = "0.1.42"
syntect = "4.5.0"
uuid = { version = "0.8.1", features = ["v4"] }
indoc = "1.0.3"
unicode-segmentation = "1.7.1"
strum = "0.20.0"
strum_macros = "0.20.0"
chrono = "0.4.19"
serde_json = "1.0.60"

[dependencies.weechat]
path = "/home/poljar/werk/misc/rust-weechat/weechat"
features = ["async", "config_macro"]

[dependencies.matrix-sdk]
path = "/home/poljar/werk/priv/nio-rust/matrix_sdk"
branch = "crypto-improvements"
