[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["cdylib"]

[dependencies]
url = "2.1.1"
tokio = { version = "0.2.22", features = [ "rt-threaded", "sync" ] }
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
async-std = { version = "1.6.3", features = [ "unstable" ] }
clap = "2.33.3"
async-trait = "0.1.40"
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.weechat]
version = "0.3.1"
features = ["async", "config_macro"]

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
