[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.67"
futures = "0.3.4"
url = "2.1.1"
tokio = { version = "0.2.11", features = [ "rt-threaded" ] }
async-std = { version = "1.5.0", features = [ "unstable" ] }
async-task = "1.3.1"
pipe-channel = "1.3.0"
clap = "2.33.0"

matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk" }

weechat = { git = "https://github.com/poljar/rust-weechat/" }
weechat-sys = { git = "https://github.com/poljar/rust-weechat/" }
